### PR TITLE
Add stringForOpcode function to opcodes lib. Resolves #55

### LINKED ISSUE #55: Add stringForOpcode function
- [ ] add function `stringForOpcode(opcode: int) : string`
  - For opcodes `0x01`-`0x4b`  returns a string in the format `PUSH_DATA(n)` where n is the number of bytes that will be pushed onto the stack.
  - For all other opcodes, the result of `wordForOpcode` is returned.

The immediate use case for this is the cli which attempts to display a the term for a push_data opcodes when `undefined` is returned.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by JBaczuk — CHANGES_REQUESTED** [review]
It would be nice to also include the fix to the cli in this PR, so it's clear what you were intending. Can we merge the cli PR and then add it to this?

**Comment by wardlem** [comment]
> It would be nice to also include the fix to the cli in this PR, so it's clear what you were intending. Can we merge the cli PR and then add it to this?

Sounds good.

**Comment by wardlem** [comment]
@JBaczuk This has been updated.

**Review by JBaczuk — APPROVED** [review]
Seems to work, and looks good to me!

**Pull request merged**
