### PR TITLE
Added address conversion convenience functions. Resolves #37

### LINKED ISSUE #37: Address conversion convenience methods
Add the following convenience methods:

1. `asmToAddress(options = {})`
2. `addressToAsm(options = {})`
3. `rawToAddress(optionsOrEncoding = {})`
4. `addressToRaw(optionsOrEncoding = {})`

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by wardlem** [comment]
This PR requires a consideration of what a templating ASM syntax should look like.  Currently, it looks like `OP_HASH160 <20-byte-script-hash> OP_EQUAL`.  The template processor sees that the script begins with `20-byte` and enforces that the push_data value is 20 bytes.  This works ok, though it isn't perfect.  The templating language currently doesn't support opcode parameters, which are required in a p2ms template (for *m* and *n*). For this, I was considering `<OP_1-OP_16> and it would see that it expects an op within that range.  The public keys also need to be repeated, and this needs a syntax.  I was considering, for the public keys `<33-byte-public-key...>` where the ... indicates repetition.

I am not sold on any of these choices.

**Review by JBaczuk — COMMENTED** [review]
<strike>How does this work?

I tried:
```
const bs = require('./')
undefined
> bs.rawToAddress(Buffer.from('3a38d44d6a0c8d0bb84e0232cc632b7e48c72e0e', 'hex'))
undefined
> script = bs.fromRaw(Buffer.from('3a38d44d6a0c8d0bb84e0232cc632b7e48c72e0e', 'hex'))
BScript {
  tokens:
   [ Token {
       type: 'LITERAL',
       value: <Buffer 38 d4 4d 6a 0c 8d 0b b8 4e 02 32 cc 63 2b 7e 48 c7 2e 0e 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
       startIndex: 0,
       endIndex: 59 } ] }
> script.rawToAddress()
TypeError: script.rawToAddress is not a function
> bs.rawToAddress(script)
TypeError: Raw script must be a string or buffer
    at Function.fromRaw (/Users/Jbaczuk/Documents/Personal/bscript-parser/src/bscript.js:93:13)
    at Function.BScript.rawToAddress (/Users/Jbaczuk/Documents/Personal/bscript-parser/index.js:32:18)
```</strike>

Nevermind, i looked at the tests to figure it out.

**Review by JBaczuk — APPROVED** [review]
Is there any way to let it know which network you are on? (testnet/mainnet)?

**Comment by wardlem** [comment]
> Is there any way to let it know which network you are on? (testnet/mainnet)?

I don't think so.  The parser isn't really aware of this, it only knows what the prefixes are that you provide.

**Pull request merged**
